admin_blog:
    resource: "@AdminBlogBundle/Resources/config/routing.yml"
    prefix:   /

admin_user:
    resource: "@AdminUserBundle/Resources/config/routing.yml"
    prefix:   /

admin_admin:
    resource: "@AdminAdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
