imports:
    - { resource: "@AdminUserBundle/Resources/config/security.yml" }
    
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, role: ROLE_ADMIN }
        - { path: ^/post/new, role: ROLE_ADMIN }
        - { path: ^/post/.*/show, role: ROLE_ADMIN }
        - { path: ^/post/.*/edit, role: ROLE_ADMIN }
        - { path: ^/post/.*/delete, role: ROLE_ADMIN }
        - { path: ^/contact/new, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contact/.*/show, role: ROLE_ADMIN }
        - { path: ^/contact/.*/edit, role: ROLE_ADMIN }
        - { path: ^/contact/.*/delete, role: ROLE_ADMIN }
        - { path: ^/contact/*, role: ROLE_ADMIN }