admin_admin_adulte:
    resource: "@AdminAdminBundle/Resources/config/routing/adulte.yml"
    prefix:   /admin/adulte

admin_admin_homepage:
    path:     /admin
    defaults: { _controller: AdminAdminBundle:Default:index }
    
admin_admin_enfant:
    resource: "@AdminAdminBundle/Resources/config/routing/enfant.yml"
    prefix:   /admin/enfant    

admin_admin_produit:
    resource: "@AdminAdminBundle/Resources/config/routing/produit.yml"
    prefix:   /admin/produit
        
admin_admin_vendu:
    resource: "@AdminAdminBundle/Resources/config/routing/vendu.yml"
    prefix:   /admin/vendu   
    
admin_admin_visite:
    resource: "@AdminAdminBundle/Resources/config/routing/visite.yml"
    prefix:   /admin/visite
    
admin_admin_visitena:
    resource: "@AdminAdminBundle/Resources/config/routing/visitena.yml"
    prefix:   /admin/visitena

admin_admin_recherche:
    resource: "@AdminAdminBundle/Resources/config/routing/recherche.yml"
    prefix:   /recherche    