visitena_index:
    path:     /
    defaults: { _controller: "AdminAdminBundle:VisiteNA:index" }
    methods:  GET

visitena_show:
    path:     /{id}/show
    defaults: { _controller: "AdminAdminBundle:VisiteNA:show" }
    methods:  GET

visitena_new:
    path:     /new
    defaults: { _controller: "AdminAdminBundle:VisiteNA:new" }
    methods:  [GET, POST]

visitena_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminAdminBundle:VisiteNA:edit" }
    methods:  [GET, POST]

visitena_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminAdminBundle:VisiteNA:delete" }
    methods:  DELETE

