visite_index:
    path:     /
    defaults: { _controller: "AdminAdminBundle:Visite:index" }
    methods:  GET

visite_show:
    path:     /{id}/show
    defaults: { _controller: "AdminAdminBundle:Visite:show" }
    methods:  GET

visite_new:
    path:     /new
    defaults: { _controller: "AdminAdminBundle:Visite:new" }
    methods:  [GET, POST]

visite_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminAdminBundle:Visite:edit" }
    methods:  [GET, POST]

visite_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminAdminBundle:Visite:delete" }
    methods:  DELETE
